name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Masuk ke direktori aplikasi
          cd /home/rahulilabs27/ai-integrated/bangkit_ai

          # Pastikan deploy.sh dapat dieksekusi
          chmod +x deploy.sh

          # Jalankan script deploy.sh dengan bash
          bash deploy.sh
